version: '3.8'

volumes:
  postgres:
  postgres-data:

services:
  postgres:
    image: postgres:13
    container_name: postgres_payment_1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./.postgres-data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 10

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - LISTEN_PORT=:3000
      - POSTGRES_DB=payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_ADDR=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./.local:/local
    ports:
      - 3000:3000
